services:
  web:
    build: .
    expose:
      - "5000"
    environment:
      - CACHE_TYPE=SimpleCache
      - CACHE_DEFAULT_TIMEOUT=300
      - DNS_TIMEOUT=2
      - DNS_LIFETIME=4
      - RATELIMIT_DEFAULT=100 per day
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./app/static:/app/app/static
      - generated_files:/app/app/static/generated

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./app/static:/app/static:ro
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - web
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  redis_data:
  generated_files:
  certbot_conf:
  certbot_www:
